CREATE DATABASE CAPSTONE_PROJECT

SELECT * FROM [dbo].[SalesData]

SELECT PRODUCT, SUM(TotalSales) AS TOTALSALES FROM [dbo].[SalesData]
WHERE PRODUCT IN ('Shirt', 'Shoes', 'Hat', 'Socks', 'Jacket', 'Gloves')
GROUP BY PRODUCT

--------To get the total sales in each region-------
SELECT REGION, SUM(TotalSales) AS TOTALSALES FROM [dbo].[SalesData]
WHERE REGION IN ('North', 'South', 'East', 'West')
GROUP BY REGION

SELECT REGION, COUNT(OrderID) AS SalesTransactions FROM [dbo].[SalesData]
GROUP BY REGION


SELECT TOP 1 PRODUCT, SUM(TOTALSALES) AS HIGHESTSELLING_PRODUCT FROM [dbo].[SalesData]
GROUP BY PRODUCT


SELECT PRODUCT, SUM(TOTALSALES) AS TOTAL_REVENUE FROM [dbo].[SalesData]
GROUP BY PRODUCT

SELECT MONTH, SUM(TotalSales) AS TOTALSALESFOR2024 FROM [dbo].[SalesData]
WHERE YEAR = '2024'
GROUP BY MONTH
ORDER BY MONTH

SELECT TOP 5 CUSTOMERID, SUM(TOTALSALES) AS TOTALAMOUNTPURCHASE FROM [dbo].[SalesData]
GROUP BY CUSTOMERID
ORDER BY 2 DESC


SELECT REGION, CONVERT(DECIMAL(10, 2), (SUM(TotalSales) * 1.0 / (SELECT SUM(TotalSales) FROM [dbo].[SalesData])) * 100) AS PERCENTAGE_OF_TOTALSALES
FROM [dbo].[SalesData]
GROUP BY REGION
ORDER BY 2 DESC


SELECT PRODUCT FROM [dbo].[SalesData]
GROUP BY PRODUCT
HAVING MAX(ORDERDATE) < DATEADD(quarter, -1, GETDATE())
UNION SELECT PRODUCT FROM [dbo].[SalesData]
WHERE PRODUCT NOT IN (
SELECT PRODUCT FROM [dbo].[SalesData]
    )



